### PR TITLE
use backend defaults that will hopefully trip up front end developer less

### PR DESCRIPTION
**Pull request by sagehen03**
[//]: # (Title Template: "[TR_##] Title")

---

#### Please check if the PR fulfills these requirements

- [x] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

These changes should make it so that new developers doing a fresh checkout won't have to set up banana-rails as the default will be to talk to the AWS server. Secondarily, developers wanting to test against their own banana-rails changes can do see either via web browser or the expo app by adding a .env and specifying the network ip address where their banana-rails is running.

### CODE REVIEW

**Comment by duskcloudxu** [comment]
So if I understand it right, this change would let all front-end dev works on the remote server by default...would it be a burden for your server? Since if so all the front-end devs would debug depend on that instance and if it shut down or something they cannot continue until it's fixed.

How do you think about making localhost a default choice and remote server optional? We could tell people who debug on device or people who cannot install back-end to use the remote server.

**Comment by sagehen03** [comment]
Hey Tao, if you add `.env` file with your local ip address where you're running rails then that is the default.  I don't think it would be a burden for the server if many devs opted to not add the `.env` file.

**Review by KennyT995 — APPROVED** [review]

**Review by KennyT995 — APPROVED** [review]

**Comment by KennyT995** [comment]
looks good

**Review by KennyT995 — APPROVED** [review]
looks good

**Pull request merged**
