### PR TITLE
Form Validation Constraints

### PR DESCRIPTION
**Pull request by emarti43**
## What this PR does
* Adds `validate.js` package
* Introduces validation constraints via `@utils/constraints` for the following:
  - Client Registration
  - Donor Registration
  - Donation 

* This does **not** enforce validation constraints (not implemented) on the registration screens for Client and Donor yet. This is to reduce the number of merge conflicts that this PR may have with other branches.

Documentation and examples for `validate.js` can be found [here](https://validatejs.org/#constraints)

## Additional notes
I tried to align the constraints with what's on the [Pre-Alpha Design](https://www.figma.com/file/Kzv8b6CHHq5Y5aCuBWAGLU/THE-BANANA-APP-BGP?node-id=5374%3A36).  I'm open to modifying these constraints if needed.
### Trello Cards
* [#149](https://trello.com/c/EjwYbuJ7)
* [#153](https://trello.com/c/7uJ9zmUS)

### CODE REVIEW

**Comment by duskcloudxu** [comment]
Just want to make sure, is it for master version or for pre-alpha version? You might want to merge it into the pre-alpha branch but not the master branch : )

**Comment by emarti43** [comment]
I was planning for the validations to be available in the pre-alpha branch but I'm unsure as to how many commits that have been recently pushed in master will also be pushed to pre-alpha? I can change it to merge to prealpha, but am unsure as to which PR's will be affected [such as the side menu PR](https://github.com/FoodIsLifeBGP/banana-rn/pull/86)

**Comment by duskcloudxu** [comment]
Sorry has been busy recently. That's not the problem of your side and I guess it would not affect the existing code in pre-alpha branch. I have no problem to that if that is some preparation code for validation, good work!

**Review by duskcloudxu — DISMISSED** [review]

**Comment by emarti43** [comment]
> Sorry has been busy recently. That's not the problem of your side and I guess it would not affect the existing code in pre-alpha branch. I have no problem to that if that is some preparation code for validation, good work!

gotcha. No worries 👍. had to update some of these field to the pre-alpha but it should all be good now

**Comment by renburnett** [comment]
Looks good! Not a huge issue, but is it possible to rebase and collapse these commits into just one or two commits?

**Review by duskcloudxu — APPROVED** [review]
no problem from my side : )

**Pull request merged**
