### PR TITLE
alertmodal should be null on empty alert(android)

### PR DESCRIPTION
**Pull request by emarti43**
## Fix
Addresses issue when Android version couldn't dismiss AlertModals.
**Trello Card** [#205](https://trello.com/c/GBHgGUtn)
## How to test
* set initial Global state to have an alert
* ensure AlertModal is dismissable

### CODE REVIEW

**Comment by duskcloudxu** [comment]
Looks good, I think it would be better if there is a comment explaining why to add this line while there is some similar logic in `open` props in `<Modal>` below?

**Comment by emarti43** [comment]
While `display: block` can work in some components, It doesn't work in this particular case, as there is an issue with [components still displaying on Android](https://github.com/facebook/react-native/issues/18415)

**Comment by duskcloudxu** [comment]
Thanks for doing the research, I mean we could add the explanation as comment around the code you added lol

**Comment by emarti43** [comment]
> Thanks for doing the research, I mean we could add the explanation as comment around the code you added lol

gotcha haha. Will do that in a bit

**Review by duskcloudxu — APPROVED** [review]
Good job！

**Pull request merged**
