### PR TITLE
Donation details screen, plus ability to cancel donation.

### PR DESCRIPTION
**Pull request by sagehen03**
[//]: # (Title Template: "[TR_##] Title")

---

#### Please check if the PR fulfills these requirements

- [x] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

---

#### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
New feature.

#### What is the current behavior? (You can also link to an open issue here)
Clicking on a donation in the donation list view does nothing.

#### What is the new behavior? (if this is a feature change)
Clicking on a donation in the donation list view brings you to the donation details screen where you can cancel the donation.

#### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No.

#### Images (before/ after screenshots, interaction GIFs, ...)

---

### CODE REVIEW

**Comment by duskcloudxu** [comment]
image
Seems there is a layout problem on IOS simu. Also when I clicked the cancel donation, there is no response from IOS simu, and the donation is still there, here is the back-end log
image
Not sure if that's caused by my local back-end or a bug.

**Comment by sagehen03** [comment]
Hey Tao, 
Thanks for testing on iOS--that's not something I can do since I don't use Apple so it might be easier for you to test.  I can take a shot at adding some more margin in the case of iOS, but it would be faster if you did it most likely.  The cancel donation API call was probably failing before because https://github.com/FoodIsLifeBGP/banana-rails/pull/91 hadn't been merged or deployed to the staging server.  Since Deepali recently approved and merged it, it should work now against the staging backend or the latest from prealpha/main if you're running banana-rails locally now.

**Review by duskcloudxu — APPROVED** [review]
The layout is good after you merged prealpha, and it works good with lastest backend! good work!

**Comment by dbiradar** [comment]
Web version shows an active donations. If I click on it, it takes me to details and lets me cancel the donation as well.

**Pull request merged**
